# Generated by Django 4.0.4 on 2022-05-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_lotcode_alter_lot_lot_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='lot_code',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='LotCode',
        ),
    ]
