# Generated by Django 4.0.4 on 2022-05-10 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_lot_lot_code_delete_lotcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='generic_info',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='lot',
            name='hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='tx_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
