# Generated by Django 4.0.4 on 2022-05-10 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_lot_generic_info_remove_lot_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='generic_info',
            field=models.TextField(null=True),
        ),
    ]
