# Generated by Django 4.0.4 on 2022-05-11 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lot',
            old_name='author',
            new_name='created_by',
        ),
    ]
