# Generated by Django 4.0.4 on 2022-05-11 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_author_lot_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='image',
        ),
    ]
