# Generated by Django 4.0.4 on 2022-05-11 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_lot_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lot',
        ),
    ]
